spring.application.name=employee-management
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_sys
spring.datasource.username=postgres
spring.datasource.password=246813579
#spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
